name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deplyment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Lint code
        run: npm run eslint
      - name: Build front
        run: npm run build
      - name: Test code
        run: npm run test
      - name: Test e2e
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30